---
_extends: gh-labels

repository:
  name: web
  description: 'Web UI for OpenCloud built with Vue.js and TypeScript'
  homepage: https://opencloud.eu
  has_wiki: false

labels:
  - name: Topic:Accessibility
    oldname: Accessibility
    color: "#ccf4ff"
  - name: Topic:Extensions-framework
    oldname: extensions framework
    color: "#ccf4ff"
  - name: feature:files
    color: "#d4c5f9"
  - name: feature:text-editor
    color: "#d4c5f9"
  - name: feature:pdf-viewer
    color: "#d4c5f9"
  - name: feature:preview
    color: "#d4c5f9"

...
