x-opencloud-server: &opencloud-service
  image: ${OC_IMAGE:-opencloudeu/opencloud-rolling:daily}
  entrypoint: /bin/sh
  command: ['-c', 'opencloud init || true && opencloud server']
  environment: &opencloud-environment
    OC_INSECURE: '${OC_INSECURE:-true}'
    OC_LOG_LEVEL: '${OC_LOG_LEVEL:-error}'
    OC_LOG_PRETTY: '${OC_LOG_PRETTY:-true}'
    OC_LOG_COLOR: '${OC_LOG_COLOR:-true}'
    OC_PASSWORD_POLICY_MIN_CHARACTERS: '3'
    OC_PASSWORD_POLICY_MIN_LOWERCASE_CHARACTERS: '0'
    OC_PASSWORD_POLICY_MIN_UPPERCASE_CHARACTERS: '0'
    OC_PASSWORD_POLICY_MIN_DIGITS: '0'
    OC_PASSWORD_POLICY_MIN_SPECIAL_CHARACTERS: '0'
    OC_PASSWORD_POLICY_BANNED_PASSWORDS_LIST: '/etc/opencloud/password-policy-banned-passwords.txt'
    OC_SHOW_USER_EMAIL_IN_RESULTS: 'true'
    ACTIVITYLOG_WRITE_BUFFER_DURATION: '0'

    # WEB
    WEB_ASSET_CORE_PATH: ${WEB_ASSET_CORE_PATH:-/web/dist}
    WEB_ASSET_APPS_PATH: ${WEB_ASSET_APPS_PATH:-/web/apps}
    WEB_UI_CONFIG_FILE: ${WEB_UI_CONFIG_FILE:-/web/config.json}

    #FRONTEND
    FRONTEND_SEARCH_MIN_LENGTH: '2'
    FRONTEND_OCS_ENABLE_DENIALS: 'true'
    FRONTEND_FULL_TEXT_SEARCH_ENABLED: 'true'
    GRAPH_INCLUDE_OCM_SHAREES: 'true'

    # IDM
    IDM_CREATE_DEMO_USERS: '${DEMO_USERS:-true}'
    IDM_ADMIN_PASSWORD: '${ADMIN_PASSWORD:-admin}' # override the random admin password from `opencloud init`
    IDM_SVC_PASSWORD: '${IDM_SVC_PASSWORD:-some-ldap-idm-password}'
    IDM_REVASVC_PASSWORD: '${IDM_REVASVC_PASSWORD:-some-ldap-reva-password}'
    IDM_IDPSVC_PASSWORD: '${IDM_IDPSVC_PASSWORD:-some-ldap-idp-password}'

    # IDP
    IDP_LDAP_BIND_PASSWORD: '${IDP_LDAP_BIND_PASSWORD:-some-ldap-idp-password}'

    # STORAGE
    STORAGE_USERS_DRIVER: '${STORAGE_USERS_DRIVER:-posix}'
    STORAGE_USERS_ID_CACHE_STORE: 'nats-js-kv'
    STORAGE_TRANSFER_SECRET: '${STORAGE_TRANSFER_SECRET:-some-opencloud-transfer-secret}'

    # LDAP
    GROUPS_LDAP_BIND_PASSWORD: '${GROUPS_LDAP_BIND_PASSWORD:-some-ldap-reva-password}'
    USERS_LDAP_BIND_PASSWORD: '${USERS_LDAP_BIND_PASSWORD:-some-ldap-reva-password}'
    AUTH_BASIC_LDAP_BIND_PASSWORD: '${AUTH_BASIC_LDAP_BIND_PASSWORD:-some-ldap-reva-password}'
    GRAPH_APPLICATION_ID: '${GRAPH_APPLICATION_ID:-some-graph-app-id}'
    GRAPH_LDAP_BIND_PASSWORD: '${GRAPH_LDAP_BIND_PASSWORD:-some-ldap-idm-password}'
    LDAP_GROUP_SUBSTRING_FILTER_TYPE: 'any'
    LDAP_USER_SUBSTRING_FILTER_TYPE: 'any'

    # PROXY
    PROXY_ENABLE_BASIC_AUTH: '${PROXY_ENABLE_BASIC_AUTH:-true}'
    PROXY_TLS: 'false'

    # TIKA
    SEARCH_EXTRACTOR_TYPE: 'tika'
    SEARCH_EXTRACTOR_TIKA_TIKA_URL: 'http://host.docker.internal:9998'
    SEARCH_EXTRACTOR_CS3SOURCE_INSECURE: 'true'

    # App Provider
    GATEWAY_GRPC_ADDR: 0.0.0.0:9142 # make the REVA gateway accessible to the app drivers
    NATS_NATS_HOST: 0.0.0.0
    NATS_NATS_PORT: 9233

    # OCM
    OCM_OCM_PROVIDER_AUTHORIZER_PROVIDERS_FILE: '/etc/opencloud/ocmproviders.json'
    OCM_OCM_INVITE_MANAGER_INSECURE: 'true'
    OCM_OCM_SHARE_PROVIDER_INSECURE: 'true'
    OCM_OCM_STORAGE_PROVIDER_INSECURE: 'true'

  extra_hosts:
    - host.docker.internal:${DOCKER_HOST:-host-gateway}
    - oc.opencloud.test:${DOCKER_HOST:-host-gateway}
  restart: unless-stopped
  depends_on:
    - traefik
    - tika-service

services:
  opencloud:
    <<: *opencloud-service
    container_name: web_oc
    environment:
      <<: *opencloud-environment
      OC_URL: ${OC_URL:-https://host.docker.internal:9200}
      OC_CORS_ALLOW_ORIGINS: https://host.docker.internal:9200,https://host.docker.internal:9201
      OCM_WEBAPP_TEMPLATE: https://host.docker.internal:9201/o/{{.Token}}/{relative-path-to-shared-resource}
      # make the registry available to the app provider containers
      MICRO_REGISTRY: 'nats-js-kv'
      MICRO_REGISTRY_ADDRESS: 0.0.0.0:9233
      PROXY_CSP_CONFIG_FILE_LOCATION: /etc/opencloud/csp.yaml
      COLLABORA_DOMAIN: host.docker.internal:9980
      FRONTEND_APP_HANDLER_SECURE_VIEW_APP_ADDR: eu.opencloud.api.collaboration.Collabora
      # Needed for enabling all roles
      GRAPH_AVAILABLE_ROLES: b1e2218d-eef8-4d4c-b82d-0f1a1b48f3b5,a8d5fe5e-96e3-418d-825b-534dbdf22b99,fb6c3e19-e378-47e5-b277-9732f9de6e21,58c63c02-1d89-4572-916a-870abc5a1b7d,2d00ce52-1fc2-4dbc-8b95-a73b73395f5a,1c996275-f1c9-4e71-abdf-a42f6495e960,312c0871-5ef7-4b3a-85b6-0e4074c64049,aa97fe03-7980-45ac-9e50-b325749fd7e6,63e64e19-8d43-42ec-a738-2b6af2610efa
    labels:
      traefik.enable: true
      traefik.http.routers.opencloud.tls: true
      traefik.http.routers.opencloud.rule: Host(`host.docker.internal`) && PathPrefix(`/`)
      traefik.http.routers.opencloud.entrypoints: opencloud
      traefik.http.services.opencloud.loadbalancer.server.port: 9200
      traefik.http.routers.opencloud.middlewares: cors
    volumes:
      - ./dev/docker/opencloud/csp.yaml:/etc/opencloud/csp.yaml
      - ./dev/docker/opencloud/proxy.yaml:/etc/opencloud/proxy.yaml
      - ./dev/docker/opencloud/password-policy-banned-passwords.txt:/etc/opencloud/password-policy-banned-passwords.txt
      - ./dev/docker/opencloud.idp.config.yaml:/etc/opencloud/idp.yaml
      - ./dev/docker/opencloud-ca:/var/lib/opencloud/proxy
      - ./dev/docker/opencloud.storage.ocmproviders.json:/etc/opencloud/ocmproviders.json
      - ./dev/docker/apps:/web/apps
      - ./dist:/web/dist
      - ./dev/docker/opencloud/app-registry.yaml:/etc/opencloud/app-registry.yaml
      - opencloud-config:/etc/opencloud
      - ${OC_WEB_CONFIG:-./dev/docker/opencloud.web.config.json}:/web/config.json:ro

  opencloud-federated:
    <<: *opencloud-service
    container_name: web_opencloud_federated
    environment:
      <<: *opencloud-environment
      OC_URL: https://oc.opencloud.test:10200
      OC_CORS_ALLOW_ORIGINS: https://oc.opencloud.test:10201
      OCM_WEBAPP_TEMPLATE: https://oc.opencloud.test:10201/o/{{.Token}}/{relative-path-to-shared-resource}
    labels:
      traefik.enable: true
      traefik.http.routers.opencloud-federated.tls: true
      traefik.http.routers.opencloud-federated.rule: Host(`oc.opencloud.test`) && PathPrefix(`/`)
      traefik.http.routers.opencloud-federated.entrypoints: opencloud-federated
      traefik.http.services.opencloud-federated.loadbalancer.server.port: 9200
      traefik.http.routers.opencloud-federated.middlewares: cors
    volumes:
      - ./dev/docker/opencloud/password-policy-banned-passwords.txt:/etc/opencloud/password-policy-banned-passwords.txt
      - ./dev/docker/opencloud.idp.config.yaml:/etc/opencloud/idp.yaml
      - ./dev/docker/opencloud-ca:/var/lib/opencloud/proxy
      - ./dev/docker/opencloud.storage.ocmproviders.json:/etc/opencloud/ocmproviders.json
      - ./dist:/web/dist
      - ./dev/docker/opencloud/app-registry.yaml:/etc/opencloud/app-registry.yaml
      - opencloud-federated-config:/etc/opencloud
      - ${OC_WEB_CONFIG:-./dev/docker/opencloud.web-federated.config.json}:/web/config.json:ro

  collaboration:
    image: ${OC_IMAGE:-opencloudeu/opencloud-rolling:daily}
    depends_on:
      opencloud:
        condition: service_started
      collabora:
        condition: service_healthy
    entrypoint:
      - /bin/sh
    command: ['-c', 'opencloud collaboration server']
    environment:
      COLLABORATION_GRPC_ADDR: 0.0.0.0:9301
      COLLABORATION_HTTP_ADDR: 0.0.0.0:9300
      MICRO_REGISTRY: nats-js-kv
      MICRO_REGISTRY_ADDRESS: opencloud:9233
      COLLABORATION_WOPI_SRC: https://${WOPISERVER_DOMAIN:-host.docker.internal:9300}
      COLLABORATION_APP_NAME: 'Collabora'
      COLLABORATION_APP_PRODUCT: 'Collabora'
      COLLABORATION_APP_ADDR: https://${COLLABORA_DOMAIN:-host.docker.internal:9980}
      COLLABORATION_APP_ICON: https://${COLLABORA_DOMAIN:-host.docker.internal:9980}/favicon.ico
      COLLABORATION_APP_INSECURE: ${INSECURE:-true}
      COLLABORATION_CS3API_DATAGATEWAY_INSECURE: ${INSECURE:-true}
      COLLABORATION_LOG_LEVEL: ${LOG_LEVEL:-info}
      OC_URL: ${OC_URL:-https://host.docker.internal:9200}
    extra_hosts:
      - host.docker.internal:${DOCKER_HOST:-host-gateway}
    volumes:
      - opencloud-config:/etc/opencloud
    labels:
      traefik.enable: true
      traefik.http.routers.collaboration.tls: true
      traefik.http.routers.collaboration.rule: PathPrefix(`/`)
      traefik.http.routers.collaboration.entrypoints: collaboration
      traefik.http.services.collaboration.loadbalancer.server.port: 9300
    logging:
      driver: ${LOG_DRIVER:-local}
    restart: unless-stopped

  collabora:
    image: collabora/code:25.04.4.1.1
    entrypoint: ['/bin/bash', '-c']
    command: ['coolconfig generate-proof-key && /start-collabora-online.sh']
    environment:
      DONT_GEN_SSL_CERT: YES
      extra_params: --o:ssl.enable=false --o:ssl.ssl_verification=false --o:home_mode.enable=true --o:ssl.termination=true --o:net.frame_ancestors=${OC_URL:-https://host.docker.internal:9200}
      username: ${COLLABORA_ADMIN_USER:-admin}
      password: ${COLLABORA_ADMIN_PASSWORD:-admin}
    cap_add:
      - MKNOD
    extra_hosts:
      - host.docker.internal:${DOCKER_HOST:-host-gateway}
    healthcheck:
      test:
        [
          'CMD',
          'bash',
          '-c',
          "exec 3<>/dev/tcp/127.0.0.1/9980 && echo -e 'GET /hosting/discovery HTTP/1.1\r\nHost: localhost:9980\r\n\r\n' >&3 && head -n 1 <&3 | grep '200 OK'"
        ]
    labels:
      traefik.enable: true
      traefik.http.routers.collabora.tls: true
      traefik.http.routers.collabora.rule: PathPrefix(`/`)
      traefik.http.routers.collabora.entrypoints: collabora
      traefik.http.services.collabora.loadbalancer.server.port: 9980
    restart: unless-stopped
    depends_on:
      - traefik

  traefik:
    image: traefik:v3.4.4
    restart: unless-stopped
    entrypoint:
      [
        '/bin/sh',
        '-c',
        "[ -f /certificates/server.key ] && ./entrypoint.sh $$@ || (apk add openssl && openssl req -subj '/CN=opencloud.test' -x509 -sha256 -nodes -days 3650 -newkey rsa:2048 -keyout /certificates/server.key -out /certificates/server.crt && chmod -R 777 /certificates && ./entrypoint.sh $$@)"
      ]
    command:
      - '--pilot.dashboard=false'
      - '--log.level=DEBUG'
      - '--api.dashboard=true'
      - '--api.insecure=true'
      - '--providers.file.directory=/configs'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.opencloud.address=:9200'
      - '--entrypoints.opencloud-federated.address=:10200'
      - '--entrypoints.collabora.address=:9980'
      - '--entrypoints.wopi.address=:8880'
      - '--entrypoints.collaboration.address=:9300'
      - '--entrypoints.collaboration-oo.address=:9302'
      - '--entrypoints.websecure.address=:443'
      - '--entrypoints.websecure.http.middlewares=https_config@docker'
      - '--entrypoints.websecure.http.tls.options=default'
    labels:
      traefik.enable: true
      traefik.http.routers.http_catchall.rule: HostRegexp(`{any:.+}`)
      traefik.http.routers.http_catchall.entrypoints: web
      traefik.http.routers.http_catchall.middlewares: https_config
      traefik.http.middlewares.https_config.headers.sslRedirect: true
      traefik.http.middlewares.https_config.headers.stsSeconds: 63072000
      traefik.http.middlewares.https_config.headers.stsIncludeSubdomains: true
      traefik.http.middlewares.cors.headers.accesscontrolallowmethods: '*'
      traefik.http.middlewares.cors.headers.accesscontrolallowheaders: '*, Authorization'
      traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist: '*'
      traefik.http.middlewares.cors.headers.accesscontrolexposeheaders: '*'
      traefik.http.middlewares.cors.headers.accesscontrolmaxage: 100
      traefik.http.middlewares.cors.headers.addvaryheader: true

    ports:
      - '80:80'
      - '8090:8080'
      - '9200:9200'
      - '9300:9300'
      - '9302:9302'
      - '10200:10200'
      - '9980:9980'
      - '8880:8880'
      - '9981:443'
    volumes:
      - './dev/docker/traefik/certificates:/certificates'
      - './dev/docker/traefik/configs:/configs'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'

  tika-service:
    image: dadarek/wait-for-dependencies:latest
    container_name: web_tika_service
    depends_on:
      - tika
    command:
      - 'wait-for -it tika:9998 -t 300'

  tika:
    image: apache/tika:3.2.1.0
    container_name: web_tika
    ports:
      - 9998:9998
    restart: unless-stopped

  radicale:
    image: ${RADICALE_DOCKER_IMAGE:-opencloudeu/radicale}:${RADICALE_DOCKER_TAG:-latest}
    container_name: web_radicale
    environment:
      RADICALE_LOG_LEVEL: ${RADICALE_LOG_LEVEL:-info}
      RADICALE_STORAGE_BACKEND: ${RADICALE_STORAGE_BACKEND:-filesystem} # Map  9201 to 5232
      RADICALE_STORAGE_FILESYSTEM_FOLDER: /data
    ports:
      - '5232:5232'
    volumes:
      - ./dev/docker/radicale/data:/data
    restart: unless-stopped

volumes:
  uploads:
  opencloud-config:
  opencloud-federated-config:

networks:
  traefik:
