name: 🐛 Bug report
labels: Type:Bug
description: Help us find bugs
body:
  - type: checkboxes
    id: initial-checklist
    attributes:
      label: Initial Checklist
      options:
        - label:
            I understand this is a bug report and questions should be posted in
            the [Community Discussions](https://github.com/orgs/opencloud-eu/discussions/)
          required: true
        - label:
            I searched
            [issues](https://github.com/opencloud-eu/web/issues?q=is%3Aissue)
            and couldn’t find anything (or linked relevant results below)
          required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: Briefly describe the bug.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Reproduction Steps
      description:
        How did this happen? Please provide a [minimal, reproducible
        example](https://stackoverflow.com/help/minimal-reproducible-example).
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Outcome
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Outcome
      description: What actually happened?
    validations:
      required: true
