name: 🚀 Feature request
labels: Type:Feature
description: Share an idea for the Web UI
body:
  - type: checkboxes
    id: initial-checklist
    attributes:
      label: Initial Checklist
      options:
        - label:
            I understand this is a feature request and questions should be posted in
            the [Community Discussions](https://github.com/orgs/opencloud-eu/discussions/)
          required: true
        - label:
            I searched
            [issues](https://github.com/opencloud-eu/web/issues?q=is%3Aissue)
            and couldn’t find anything (or linked relevant results below)
          required: true
  - type: textarea
    id: idea
    attributes:
      label: Idea
      description: Briefly describe what you'd like to achieve.
    validations:
      required: true
