name: 👩🏽‍💻 User story
labels: Type:Story
description: Share an idea with clear user value
body:
  - type: checkboxes
    id: initial-checklist
    attributes:
      label: Initial Checklist
      options:
        - label:
            I understand this is a user story and questions should be posted in
            the [Community Discussions](https://github.com/orgs/opencloud-eu/discussions/)
          required: true
        - label:
            I searched
            [issues](https://github.com/opencloud-eu/web/issues?q=is%3Aissue)
            and couldn’t find anything (or linked relevant results below)
          required: true
  - type: textarea
    id: story
    attributes:
      label: User Story
      description: As a ..., I want to ... so that ... (stick to whom, what, why)
      value: As a ..., I want to ... so that ... (stick to whom, what, why)
    validations:
      required: true
  - type: textarea
    id: value
    attributes:
      label: User Value
      description: Explain the benefit or value this enhancement will bring to users.
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: List the specific conditions that must be met for the user story to be considered complete.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Reminder - Definition of Ready
        - Everyone understands the value in the user story
        - Acceptance criteria are defined
        - All dependencies are identified
        - Feature is seen from an end user's perspective
        - Story is estimated
        - Story points are under 20

        ## Reminder - Definition of Done
        - Described functionality works
        - Acceptance criteria are met
        - Critical code has unit tests
        - Prominent features have E2E tests
        - PR checks are green
