<?php
/**
 * Roundcube custom configuration for OpenCloud dev stack.
 * see https://medium.com/@matthias2handy/from-seafile-to-opencloud-building-a-self-hosted-webmail-cloud-integration-on-kubernetes-a4f3bb795d6f
 *
 * This file is mounted as zzz-custom.php so it loads after the default config
 * generated by the Docker image's entrypoint.
 */

// IMAP
$config['imap_host'] = 'stalwart:143';

// SMTP (port 25, no auth needed for local delivery)
$config['smtp_host'] = 'stalwart:25';
$config['smtp_user'] = '';
$config['smtp_pass'] = '';

// Database (SQLite for dev simplicity)
$config['db_dsnw'] = 'sqlite:////var/roundcube/db/roundcube.db?mode=0646';

// Session settings for iframe embedding
$config['session_lifetime'] = 600;        // 10 hours (in minutes)
$config['session_samesite'] = 'None';     // required for cross-origin iframe
$config['use_https'] = true;              // SameSite=None requires Secure flag

// Disable IP check (container IPs change)
$config['ip_check'] = false;

// Product name
$config['product_name'] = 'OpenCloud Mail';

// Allow all origins for development
$config['x_frame_options'] = false;

// Logging
$config['log_driver'] = 'stdout';

// Plugins
$config['plugins'] = [];
